### ISSUE TITLE
Vastag Wrapper <VASTAdTagURI>

### ISSUE THREAD

**Issue by phuongnhh7** [theonion/videojs-vast-plugin#29]
I can not tracking click for ClickTracking, but i can tracking for ClickThrough

Please help me, Thanks a lot.

**Comment by sonicsoul** [comment]
Did you solve that problem? 
I am running into the same issue here with a vast-wrapper i tried to load. The Clickthru-URL gets fired, but the clicktracking from the first XML is ignored.. any Ideas here?
