### ISSUE TITLE
Support for Postroll

### ISSUE THREAD

**Issue by jpike88** [theonion/videojs-vast-plugin#71]
I want to write code to handle that, but I'd rather not butcher the code (thought I will if I have to).

Is there anyone actually working on this??

**Comment by jpike88** [comment]
Not like anyone will ever see this, but I found something:

https://github.com/LEtudiantFork/videojs-vast-plugin

RIP theonion developers

**Comment by premesh** [comment]
Isnt that 2 years old :)

**Comment by jpike88** [comment]
Yep, I can't believe they haven't even touched the pull request, what the hell is point of keeping such an old repo online?
