### ISSUE TITLE
Clicktracking gets ignored when using VASTAdTagURI

### ISSUE THREAD

**Issue by sonicsoul** [theonion/videojs-vast-plugin#96]
Hi there, 
I am running into an issue here with a vast-wrapper i tried to load. The clickthru-URL from the second XML gets fired, but the clicktracking from the first XML is ignored.. any Ideas here? 

Additional Question: 
The second XML also has a node "AdParameters" with content and some VAST-extensions declared at the bottom. Could that be a show stopper? 

Would be thankful for any suggestions!

Cheers,
Steve

**Comment by hwde** [comment]
I assume you use a newer version of vast-client, the property for clickTracking URLs has changed to clickTrackingURLTemplate**s** and it is already an array, if you change around line #196 from

```
                        var clicktrackers = player.vastTracker.clickTrackingURLTemplate;
                        if (clicktrackers) {
                            player.vastTracker.trackURLs([clicktrackers]);
                        }
```

to

```
                        var clicktrackers = player.vastTracker.clickTrackingURLTemplates;
                        if (clicktrackers) {
                            player.vastTracker.trackURLs(clicktrackers);
                        }

```

it should track ...

**Comment by sonicsoul** [comment]
Hey man, 

thank you for sorting that out. I was already looking at that line and wondering if it was an array or not. Will try that now and get back to you, 

thanks again,
steve

**Comment by hwde** [comment]
Please note also the trailing "s" 😊

Von unterwegs gesendet.

**Comment by sonicsoul** [comment]
Hey, 
I forgot to get back to you yesterday, clicktracking is working fine again, thanks !! 

Cheers,
Steve
